# Generated by Django 5.2.5 on 2025-09-17 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conjunto de Conhecimento',
                'verbose_name_plural': 'Conjuntos de Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('BOOLEAN', 'Sim/Não'), ('DATE', 'Data'), ('URL', 'URL'), ('JSON', 'JSON')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='knowledge_base.knowledgebaseset')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='knowledge_base.knowledgebaseset')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='knowledge_base.knowledgebaseentry')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.knowledgebasefield')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'unique_together': {('entry', 'field')},
            },
        ),
    ]
