services:
  db:
    image: postgres:15
    container_name: crm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - loomie-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: crm_backend:latest
    container_name: crm_backend
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "crm.backend.localhost"
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - loomie-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: crm_frontend:latest
    container_name: crm_frontend
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - loomie-network

volumes:
  postgres-data:

networks:
  loomie-network:
    external: true
