# Generated by Django 5.2.5 on 2025-09-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='whatsapp_id',
            field=models.CharField(blank=True, help_text='ID da mensagem no WhatsApp', max_length=100, null=True),
        ),
    ]
