# Generated by Django 5.2.5 on 2025-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_negocio_atualizado_em_alter_contato_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem das colunas no Kanban', unique=True),
        ),
    ]
