# Generated by Django 5.2.5 on 2025-10-18 16:43

import django.db.models.deletion
import django.utils.timezone
import usuario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plano', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adquirido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('vence_em', models.DateTimeField(default=usuario.models.default_vencimento)),
                ('plano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
