# Generated by Django 5.2.5 on 2025-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_planousuario_plano_alter_planousuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planousuario',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
    ]
