# Generated by Django 5.2.5 on 2025-10-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_planousuario_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planousuario',
            name='dummy_field',
        ),
    ]
