# Generated by Django 5.2.5 on 2025-10-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aceitou_quando',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
