# Generated by Django 5.2.5 on 2025-10-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_planousuario_dummy_field'),
    ]

    operations = [
    ]
