# Generated by Django 5.2.5 on 2025-10-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20251029_1739'),
    ]

    operations = [
    ]
