# Generated by Django 5.2.5 on 2025-09-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanban',
            name='estagios',
        ),
        migrations.AddField(
            model_name='estagio',
            name='kanban',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanban.kanban'),
            preserve_default=False,
        ),
    ]
