# Generated by Django 5.2.5 on 2025-09-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('entrada', 'Entrada'), ('atendimento', 'Em Atendimento'), ('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('perdida', 'Perdida')], default='entrada', max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=200, null=True)),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('site', 'Site'), ('presencial', 'Presencial'), ('redes_sociais', 'Redes Sociais')], default='whatsapp', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='contato.contato')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='contato.operador')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('remetente', models.CharField(choices=[('cliente', 'Cliente'), ('operador', 'Operador'), ('sistema', 'Sistema')], max_length=10)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('arquivo', 'Arquivo'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('imagem', 'Imagem'), ('localizacao', 'Localização'), ('contato', 'Contato')], default='texto', max_length=15)),
                ('lida', models.BooleanField(default=False)),
                ('respondida', models.BooleanField(default=False)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos_interacao/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_id', models.CharField(blank=True, help_text='ID da mensagem no WhatsApp', max_length=100, null=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='atendimento.conversa')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contato.operador')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('visualizar', 'Visualizar'), ('responder', 'Responder'), ('finalizar', 'Finalizar'), ('transferir', 'Transferir')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contato.operador')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('importante', 'Importante'), ('urgente', 'Urgente'), ('followup', 'Follow-up'), ('problema', 'Problema'), ('solucao', 'Solução')], default='info', max_length=15)),
                ('privada', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=200, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='atendimento.conversa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='contato.operador')),
            ],
            options={
                'verbose_name': 'Nota de Atendimento',
                'verbose_name_plural': 'Notas de Atendimento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_notas/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField()),
                ('tipo_mime', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='atendimento.notaatendimento')),
            ],
            options={
                'verbose_name': 'Anexo de Nota',
                'verbose_name_plural': 'Anexos de Notas',
            },
        ),
        migrations.CreateModel(
            name='RespostasRapidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atalho', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('total_usos', models.PositiveIntegerField(default=0)),
                ('ultima_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_rapidas', to='contato.operador')),
            ],
            options={
                'verbose_name': 'Resposta Rápida',
                'verbose_name_plural': 'Respostas Rápidas',
                'ordering': ['atalho'],
            },
        ),
        migrations.CreateModel(
            name='TarefaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('tempo_estimado', models.PositiveIntegerField(blank=True, help_text='Tempo estimado em minutos', null=True)),
                ('tempo_gasto', models.PositiveIntegerField(blank=True, help_text='Tempo gasto em minutos', null=True)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='contato.contato')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='atendimento.conversa')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to='contato.operador')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_responsavel', to='contato.operador')),
            ],
            options={
                'verbose_name': 'Tarefa de Atendimento',
                'verbose_name_plural': 'Tarefas de Atendimento',
                'ordering': ['data_vencimento', '-prioridade', '-criado_em'],
            },
        ),
    ]
