# Generated by Django 5.2.5 on 2025-10-02 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacao',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='interacao',
            name='lida',
        ),
        migrations.RemoveField(
            model_name='interacao',
            name='respondida',
        ),
        migrations.AddField(
            model_name='interacao',
            name='media_duration',
            field=models.IntegerField(blank=True, help_text='Duração em segundos (áudio/vídeo)', null=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='media_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='media_size',
            field=models.IntegerField(blank=True, help_text='Tamanho em bytes', null=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL da mídia no Evolution API', null=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interacao',
            name='remetente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('documento', 'Documento'), ('sticker', 'Figurinha'), ('localizacao', 'Localização'), ('contato', 'Contato'), ('outros', 'Outros')], default='texto', max_length=20),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
