# Generated by Django 5.2.5 on 2025-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_remove_interacao_anexo_remove_interacao_lida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='media_type',
            field=models.CharField(blank=True, choices=[('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('documento', 'Documento'), ('sticker', 'Sticker')], max_length=20, null=True),
        ),
    ]
