# Generated by Django 5.2.5 on 2025-10-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_interacao_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='media_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='media_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duração em segundos para áudio/vídeo', null=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='media_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tamanho em bytes', null=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL da mídia da Evolution API', null=True),
        ),
    ]
