# Generated by Django 5.2.5 on 2025-10-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_interacao_media_mimetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacao',
            name='media_type',
        ),
    ]
