# Generated by Django 5.2.5 on 2025-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_remove_interacao_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL da mídia da Evolution API', max_length=500, null=True),
        ),
    ]
