# Generated by Django 5.1.2 on 2025-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_conversa_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='atendimento_humano',
            field=models.BooleanField(default=False, help_text='Se True, o bot está pausado e o humano está atendendo'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='atendimento_humano_ate',
            field=models.DateTimeField(blank=True, help_text='Data/hora até quando o bot ficará pausado', null=True),
        ),
    ]
