# Generated by Django 5.2.5 on 2025-10-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuarios_inclusos', models.PositiveSmallIntegerField()),
                ('contatos_inclusos', models.IntegerField()),
                ('pipelines_inclusos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
