# Generated by Django 5.2.5 on 2025-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='id_plano_abacate',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
