version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

  app:
    build: .
    volumes:
      - static_volume:/app/static # <--- MUDANÇA AQUI
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8000 crm_project.wsgi:application

  nginx:
    image: nginx:1.25
    volumes:
      - static_volume:/app/static # <--- ADICIONADO
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: # <--- ADICIONADO (Define o nosso "depósito")