# Generated by Django 5.2.5 on 2025-10-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destinatario', models.CharField(max_length=200)),
                ('assunto', models.CharField(blank=True, max_length=200, null=True)),
                ('mensagem', models.TextField()),
                ('recorrencia_tipo', models.CharField(max_length=20)),
                ('valor1', models.CharField(max_length=100)),
                ('valor2', models.CharField(blank=True, max_length=100, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
