# Generated by Django 5.2.5 on 2025-10-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='criado_por',
        ),
    ]
