# Generated by Django 5.2.5 on 2025-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_tarefa_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='link_webhook_n8n',
            field=models.URLField(blank=True, null=True),
        ),
    ]
