# Generated by Django 5.2.5 on 2025-10-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_link_webhook_n8n'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='precisar_enviar',
            field=models.BooleanField(default=True),
        ),
    ]
