# Generated by Django 5.2.5 on 2025-10-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefa_precisar_enviar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
