# Generated by Django 5.2.5 on 2025-10-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_tarefa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=20),
        ),
    ]
