# Generated by Django 5.2.5 on 2025-08-21 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostasRapidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atalho', models.CharField(help_text='Ex: /saudacao', max_length=50)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_rapidas', to='contatos.operador')),
            ],
            options={
                'ordering': ['atalho'],
                'unique_together': {('operador', 'atalho')},
            },
        ),
    ]
