# Generated by Django 5.2.5 on 2025-08-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_interacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
