# Generated by Django 5.2.5 on 2025-09-10 17:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contato', '0001_initial'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('origem', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('indicacao', 'Indicação'), ('evento', 'Evento'), ('redes_sociais', 'Redes Sociais')], default='inbound', max_length=20)),
                ('probabilidade', models.PositiveIntegerField(default=50, help_text='Probabilidade de fechamento (0-100%)')),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='contato.contato')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='kanban.estagio')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='contato.operador')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
