# Generated by Django 5.2.5 on 2025-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0001_initial'),
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='atributos_personalizados',
            field=models.ManyToManyField(related_name='negocios', to='atributo.atributopersonalizavel'),
        ),
    ]
