# Generated by Django 5.2.5 on 2025-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0001_initial'),
        ('negocio', '0003_alter_negocio_atributos_personalizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='atributos_personalizados',
            field=models.ManyToManyField(blank=True, related_name='negocios', to='atributo.atributopersonalizavel'),
        ),
    ]
