# Generated by Django 5.2.5 on 2025-09-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_comentario_negocio_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-criado_em']},
        ),
    ]
