# Generated by Django 5.2.5 on 2025-10-13 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0002_remove_kanban_estagios_estagio_kanban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('evento', models.CharField(choices=[('negocio_criado', 'Negócio Criado'), ('negocio_criado_em_x_estagio', 'Negócio Criado em Estágio X'), ('negocio_estagio_trocado', 'Negócio Trocou de Estágio'), ('negocio_estagio_trocado_de_x_para_y', 'Negócio Trocou de Estágio X para Y')], max_length=50)),
                ('acao', models.CharField(help_text='Tipo de ação: ex. enviar_email, criar_tarefa, etc.', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('estagio_destino', models.ForeignKey(blank=True, help_text="Usado se o evento for 'trocado_de_x_para_y' (destino)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatilhos_destino', to='kanban.estagio')),
                ('estagio_origem', models.ForeignKey(blank=True, help_text="Usado se o evento for 'criado_em_x_estagio' ou 'trocado_de_x_para_y' (origem)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatilhos_origem', to='kanban.estagio')),
            ],
            options={
                'verbose_name': 'Gatilho',
                'verbose_name_plural': 'Gatilhos',
            },
        ),
    ]
