# Generated by Django 5.2.5 on 2025-10-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatilho', '0001_initial'),
        ('tarefas', '0006_alter_tarefa_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatilho',
            name='parametros',
        ),
        migrations.AddField(
            model_name='gatilho',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatilho',
            name='tarefa_relacionada',
            field=models.ForeignKey(blank=True, help_text="A tarefa pré-configurada a ser executada quando a ação for 'criar_tarefa'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatilhos', to='tarefas.tarefa'),
        ),
        migrations.AlterField(
            model_name='gatilho',
            name='acao',
            field=models.CharField(choices=[('enviar_email', 'Enviar Email'), ('criar_tarefa', 'Criar Tarefa')], max_length=50),
        ),
    ]
