# Generated by Django 5.2.5 on 2025-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatilho', '0002_remove_gatilho_parametros_gatilho_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatilho',
            name='acao',
            field=models.CharField(choices=[('criar_tarefa', 'Criar Tarefa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gatilho',
            name='tarefa_relacionada',
            field=models.CharField(blank=True, choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=255, null=True),
        ),
    ]
