# Generated by Django 5.2.5 on 2025-10-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatilho', '0003_alter_gatilho_acao_alter_gatilho_tarefa_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatilho',
            name='url_n8n',
            field=models.URLField(blank=True, null=True),
        ),
    ]
