# Generated by Django 5.2.5 on 2025-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0002_atributopersonalizavel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributopersonalizavel',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('date', 'Date'), ('datetime', 'DateTime'), ('time', 'Time'), ('text', 'Text')], default='string', max_length=20),
        ),
    ]
