# Generated by Django 5.2.5 on 2025-10-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0003_alter_atributopersonalizavel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributopersonalizavel',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='atributos/'),
        ),
        migrations.AlterField(
            model_name='atributopersonalizavel',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('date', 'Date'), ('datetime', 'DateTime'), ('time', 'Time'), ('text', 'Text'), ('file', 'File')], default='string', max_length=20),
        ),
        migrations.AlterField(
            model_name='atributopersonalizavel',
            name='valor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
