# Generated by Django 5.2.5 on 2025-10-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0004_atributopersonalizavel_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetAtributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('atributos', models.ManyToManyField(blank=True, related_name='presets', to='atributo.atributopersonalizavel')),
            ],
        ),
    ]
