# Generated by Django 5.2.5 on 2025-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('boa', 'Boa'), ('alerta', 'Alerta'), ('erro', 'Erro'), ('info', 'Informação')], max_length=11),
        ),
    ]
