# Generated by Django 5.2.5 on 2025-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='whatsapp_id',
            field=models.CharField(blank=True, help_text='ID do WhatsApp (número + @s.whatsapp.net)', max_length=50, null=True, unique=True),
        ),
    ]
