# Generated by Django 5.2.5 on 2025-10-24 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contato_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contato',
            constraint=models.UniqueConstraint(fields=('criado_por', 'whatsapp_id'), name='unique_contato_por_usuario'),
        ),
    ]
