# Generated by Django 5.2.5 on 2025-10-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Minha Empresa', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracao/')),
                ('cor_primaria', models.CharField(default='#1877f2', max_length=7)),
                ('cor_secundaria', models.CharField(default='#42a5f5', max_length=7)),
                ('evolution_api_url', models.URLField(default='https://evolution-api.local')),
                ('evolution_api_key', models.CharField(blank=True, max_length=200)),
                ('whatsapp_instance_name', models.CharField(default='main', max_length=100)),
                ('openai_api_key', models.CharField(blank=True, max_length=200)),
                ('elevenlabs_api_key', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
