# Generated by Django 5.2.5 on 2025-10-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do canal (ex: WhatsApp Principal)', max_length=100)),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('email', 'Email'), ('sms', 'SMS'), ('evo', 'Evolution API'), ('n8n', 'n8n Webhook'), ('outro', 'Outro')], max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Canal ativo/inativo')),
                ('prioridade', models.IntegerField(default=1, help_text='Prioridade de envio (1=maior)')),
                ('credenciais', models.JSONField(blank=True, default=dict, help_text="API keys, tokens, URLs, etc. Exemplo: {'api_key': 'xxx', 'base_url': 'https://...'}")),
                ('recebe_entrada', models.BooleanField(default=True, help_text='Recebe mensagens de entrada')),
                ('envia_saida', models.BooleanField(default=True, help_text='Envia mensagens de saída')),
                ('destinos', models.JSONField(blank=True, default=list, help_text="Lista de destinos: ['crm', 'n8n', 'outro_canal']")),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canal de Comunicação',
                'verbose_name_plural': 'Canais de Comunicação',
                'ordering': ['prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RegrasRoteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.IntegerField(default=1)),
                ('condicoes', models.JSONField(default=dict, help_text='\n        Exemplo: {\n            "canal_tipo": "whatsapp",\n            "remetente_contem": "@c.us",\n            "horario_entre": ["08:00", "18:00"]\n        }\n        ')),
                ('acoes', models.JSONField(default=dict, help_text='\n        Exemplo: {\n            "enviar_para": ["crm", "n8n"],\n            "adicionar_tag": "urgente",\n            "notificar_operador": true\n        }\n        ')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Roteamento',
                'verbose_name_plural': 'Regras de Roteamento',
                'ordering': ['prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MensagemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID único da mensagem', max_length=255, unique=True)),
                ('direcao', models.CharField(choices=[('entrada', 'Entrada (Canal → Sistema)'), ('saida', 'Saída (Sistema → Canal)')], max_length=10)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('processando', 'Processando'), ('enviada', 'Enviada'), ('erro', 'Erro'), ('falha', 'Falha')], default='recebida', max_length=20)),
                ('payload_original', models.JSONField(help_text='Payload original recebido do canal')),
                ('payload_loomie', models.JSONField(blank=True, help_text='Mensagem no formato padrão Loomie', null=True)),
                ('remetente', models.CharField(blank=True, max_length=255)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('erro_mensagem', models.TextField(blank=True, help_text='Mensagem de erro, se houver')),
                ('tempo_processamento', models.FloatField(blank=True, help_text='Tempo em segundos', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('canal_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_destino', to='message_translator.canalconfig')),
                ('canal_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_origem', to='message_translator.canalconfig')),
            ],
            options={
                'verbose_name': 'Log de Mensagem',
                'verbose_name_plural': 'Logs de Mensagens',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['message_id'], name='message_tra_message_6d4837_idx'), models.Index(fields=['status'], name='message_tra_status_2a8c1f_idx'), models.Index(fields=['criado_em'], name='message_tra_criado__a9a9af_idx')],
            },
        ),
    ]
