# Generated by Django 5.2.5 on 2025-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_translator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do webhook (ex: 'Enviar para Make.com')", max_length=100)),
                ('url', models.URLField(help_text='URL do webhook customizado', max_length=500)),
                ('ativo', models.BooleanField(default=True, help_text='Webhook ativo/inativo')),
                ('filtro_canal', models.CharField(choices=[('todos', 'Todos os Canais'), ('whatsapp', 'Apenas WhatsApp'), ('telegram', 'Apenas Telegram'), ('instagram', 'Apenas Instagram'), ('evo', 'Apenas Evolution API')], default='todos', help_text='Filtrar mensagens por canal específico', max_length=20)),
                ('filtro_direcao', models.CharField(choices=[('ambas', 'Entrada e Saída'), ('entrada', 'Apenas Entrada'), ('saida', 'Apenas Saída')], default='ambas', help_text='Filtrar por direção da mensagem', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Headers HTTP customizados. Exemplo: {"Authorization": "Bearer token123"}')),
                ('metodo_http', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', help_text='Método HTTP para enviar', max_length=10)),
                ('timeout', models.IntegerField(default=10, help_text='Timeout em segundos (padrão: 10)')),
                ('retry_em_falha', models.BooleanField(default=True, help_text='Tentar novamente em caso de erro')),
                ('max_tentativas', models.IntegerField(default=3, help_text='Máximo de tentativas (padrão: 3)')),
                ('total_enviados', models.IntegerField(default=0, help_text='Total de mensagens enviadas')),
                ('total_erros', models.IntegerField(default=0, help_text='Total de erros')),
                ('ultima_execucao', models.DateTimeField(blank=True, help_text='Última vez que foi executado', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Customizado',
                'verbose_name_plural': 'Webhooks Customizados',
                'ordering': ['-ativo', 'nome'],
            },
        ),
    ]
