# Generated by Django 5.2.5 on 2025-10-22 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_translator', '0002_webhookcustomizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canalconfig',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuário que atualizou este canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canalconfig',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou este canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemlog',
            name='processado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário/Sistema que processou esta mensagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_processadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regrasroteamento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuário que atualizou esta regra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regrasroteamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou esta regra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookcustomizado',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuário que atualizou este webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookcustomizado',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou este webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
