# Generated by Django 5.2.5 on 2025-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_translator', '0003_canalconfig_atualizado_por_canalconfig_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalconfig',
            name='destinos',
            field=models.JSONField(blank=True, default=list, help_text="[DEPRECADO] Use WebhookCustomizado. Lista de destinos: ['crm', 'n8n', 'outro_canal']"),
        ),
        migrations.AlterField(
            model_name='canalconfig',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('email', 'Email'), ('sms', 'SMS'), ('evo', 'Evolution API'), ('outro', 'Outro')], max_length=20),
        ),
    ]
